name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag that should be deployed. If not provided, the head of the branch specified will be deployed.'
        required: false

env:
  SERVICE_ID: todoservicespring
  HARNESS_PROJECT_ID: default_project
  HARNESS_ARTIFACT_SOURCE_ID: todospringboot
  HARNESS_PIPELINE_ID: rolling_deployment_pipeline
  ENVIRONMENT_ID: dev
  WAIT_FOR_PIPELINE_TO_COMPLETE: true
  DOCKERHUB_USERNAME_REF: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD_REF: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  trigger_harness_pipeline:
    name: Deploy Spring Boot App to DO K8s via Harness
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: dev
    environment:
      name: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set tag or SHA
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          fi

      - name: Install Harness CLI
        run: |
          curl -sL https://raw.githubusercontent.com/harness/harness-cli/main/scripts/install.sh | bash
          harness version

      - name: Trigger Harness Pipeline
        env:
          HARNESS_API_KEY: ${{ secrets.HARNESS_NG_API_TOKEN }}
        run: |
          harness pipeline execute \
            --project-id $HARNESS_PROJECT_ID \
            --pipeline-id $HARNESS_PIPELINE_ID \
            --api-key $HARNESS_API_KEY \
            --input "variables.VERSION=$RELEASE_TAG" \
            --wait