name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag that should be deployed. If not provided, the head of the branch specified will be deployed.'
        required: false

env:
  SERVICE_ID: todoservicespring
  HARNESS_PROJECT_ID: default_project
  HARNESS_ARTIFACT_SOURCE_ID: todospringboot
  HARNESS_PIPELINE_ID: rolling_deployment_pipeline
  ENVIRONMENT_ID: dev
  WAIT_FOR_PIPELINE_TO_COMPLETE: true
  DOCKERHUB_USERNAME_REF: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD_REF: ${{ secrets.DOCKERHUB_PASSWORD }}
  HARNESS_NG_API_TOKEN: ${{ secrets.HARNESS_NG_API_TOKEN }}
  HARNESS_ACCOUNT_ID: ${{ secrets.HARNESS_ACCOUNT_ID }}

jobs:
  deploy-to-harness:
    name: Deploy Spring Boot App to DO K8s via Harness
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set RELEASE_TAG env variable
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          fi

      - name: Download Harness CLI (x86_64)
        run: |
            curl -LO https://github.com/harness/harness-cli/releases/download/v0.0.29/harness-v0.0.29-linux-amd64.tar.gz
            tar -xvf harness-v0.0.29-linux-amd64.tar.gz
            chmod +x harness
            sudo mv harness /usr/local/bin/
      

      - name: Trigger Harness Pipeline
        run: |
          harness pipeline execute \
            --account $HARNESS_ACCOUNT_ID \
            --project $HARNESS_PROJECT_ID \
            --pipeline $HARNESS_PIPELINE_ID \
            --token $HARNESS_NG_API_TOKEN \
            --input-set-values VERSION=$RELEASE_TAG,COMMIT_SHA=$GITHUB_SHA
